### PR TITLE
process: Add process functions

### PR DESCRIPTION
**Pull request by ashcrow**
This includes downloading packages and submitting them to hashing
services.

PTAL @jasinner  as this interfaces with the Java Hash Service.

### CODE REVIEW

**Comment by jasinner** [comment]
So far so good. I was expecting to see some git diffing going on with the victims-cve-db repository in order to determine the files to submit. Or does it act of a webhook from victims-cve-db?
Will there also be code for downloading from Maven?

**Comment by ashcrow** [comment]
> So far so good.

😸 

> I was expecting to see some git diffing going on with the victims-cve-db repository in order to determine the files to submit.

I have the start of looking at the changes in the code already but just haven't finished it.

> Or does it act of a webhook from victims-cve-db?

When we merge a PR to the victims-cve-db GitHub will send a notification with the change to this bot. This bot will look to see if:

1. The change was committed by someone other than itself
2. The change adds a file to the cve db portion of the repo

If the above are both true then the bot:

1. Clones the repository locally
2. Looks at each added file in the merge related to the cve db
  - Downloads the artifact
  - Passes the artifact to the proper hashing service
  - Gets the results from the hashing service
  - Updates the cve db file itself with hashes
  - Commits the updated file
3. Pushes the commits to the cve db

Clients will end up being updated (per previous discussions) to pull from the cve-db via git for updates rather than a remote service

> Will there also be code for downloading from Maven?

With PURL we will eventually be able to translate from a maven URI to a download location. For now we'll want to use a URI such as ``http://central.maven.org/maven2/org/springframework/spring-core/5.0.2.RELEASE/spring-core-5.0.2.RELEASE.jar``. In either case we will want to add a field to the cve-db. Maybe ``package-uri``? We can then use it for ``http`` now but later also support PURL. 

Validation would be done by the person merging the PR. It's up to them to review the pull to ensure the package url is the right one 😄.

Thoughts?

**Comment by ashcrow** [comment]
And to keep backwards compat for a short period of time we can host the result of current API output as a static file at the same location for a few months.

**Comment by ashcrow** [comment]
@jasinner recent pushes should show the logic flow better. The types will probably move into common in the near future but for now I'm keeping them within local packages.

**Comment by jasinner** [comment]
Looks great

**Pull request merged**
